apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra-eye
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None   # Headless — stable DNS for StatefulSet
